version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      fontawesome:
        patterns:
          - '@fortawesome/*'
      npm-minor-and-patch:
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
